version: '3.8'

services:
  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: solar-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_/var/opt/mssql
    networks:
      - solar-network

  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: solar-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=solar_monitoring
    volumes:
      - mongodb_data:/data/db
    networks:
      - solar-network

  # Redis
  redis:
    image: redis:7.2-alpine
    container_name: solar-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_/data
    networks:
      - solar-network

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: solar-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - solar-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: solar-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - solar-network

  # Spring Boot Application
  solar-app:
    build: .
    container_name: solar-monitoring-app
    depends_on:
      - sqlserver
      - mongodb
      - redis
      - kafka
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=SolarDB;encrypt=false
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/solar_monitoring
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - solar-network
    restart: unless-stopped

volumes:
  sqlserver_
  mongodb_
  redis_

networks:
  solar-network:
    driver: bridge