server:
  port: 8082

spring:
  application:
    name: solar-kafka-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: solar-kafka-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.solar.monitoring.system.*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.solar.monitoring.system: DEBUG
    org.springframework.kafka: INFO