server:
  port: 8081

spring:
  application:
    name: solar-redis-service

  data:
    redis:
      host: localhost
      port: 6379
      password: solar.redis
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.solar.monitoring.system: DEBUG